[package]
name = "picsteg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive"] }
image = { version = "0.24.3" }

[dev-dependencies]
tempdir = { version = "0.3.7" }
